### ISSUE TITLE
Stopped timers appear to default to 5 minutes rather than retaining their initial value

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/kitime#16]
* create a new timer, and give it a setting of something other than 5 minutes
* go back to the main timer screen
* go into the original timer again. It has defaulted back to 5 mins
* the website does retain the value.

The timers should probably retain whatever value we set for time.

**Comment by drewsdunne** [comment]
Yeah I noticed this too, it actually only happens with the person in control. The reason it does this is because I have the code upload whoever is in control's selected time, and then everyone else's will switch to that. But the code for reading the value is handled the same on everyone's so in order to avoid an endless loop, I had to make it so the person in control does not retain the value upon a switch. The problem with this is what you found, when you initially open a timer, it starts on 5 minutes (which is what I set it at when I created the UIPickerView object. I can think of a way to fix this bug though.

**Comment by andyburnett** [comment]
Maybe we should have a local variable ( on the current owners device ) that holds the initial time that was set  when the clock began. On cancel it would reset to that variable's value. Then, on loss of ownership it would be set to null.

**Comment by drewsdunne** [comment]
Yeah, I can do some version of that. I have a couple ideas, really I just need a way to differentiate between when he has set the time or when the server needs to set time time. I think I could do this with a Boolean value fairly quickly.
