### ISSUE TITLE
The Sign Out button doesn't change the UI

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/kitime#19]
Signing out of the app does appear to work, but the sign out button doesn't give users the chance to sign in again.  Pressing the + button invites the user to create a new timer, but then crashes

**Comment by drewsdunne** [comment]
Yeah I noticed this issue to, I was going to change the whole UI so that there is a sign in screen. Then you can choose to either skip the sign in and have a view-only system or sign in and then have the regular app, and the sign out button would kick you back to the sign in screen. Does that sound like a good idea?

**Comment by andyburnett** [comment]
Sounds like a very good solution

**Comment by dsl101** [comment]
Hi! Having not seen the app, nor had anything to do with its development, I
thought I'd take the opportunity to grow random ideas at it and see what
happens :)

I'm not sure if this is the scenario you're talking about, but I have a
feeling I've been frustrated by UIs with this kind of extra step before.
Rather than a signin screen, could it not default to the read only view,
with a discrete signin button for those control freaks who feel the need?
It might mean less clicks overall...

Or, it might be completely irrelevant. In which case, I will post my idea
to a different random project.

On Thursday, July 16, 2015, andyburnett <notifications@github.com> wrote:

> Sounds like a very good solution
>
> On Thu, Jul 16, 2015 at 3:58 PM, drewsdunne <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Yeah I noticed this issue to, I was going to change the whole UI so that
> > there is a sign in screen. Then you can choose to either skip the sign in
> > and have a view-only system or sign in and then have the regular app, and
> > the sign out button would kick you back to the sign in screen. Does that
> > sound like a good idea?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/Knowinnovation/kitime/issues/19#issuecomment-122071187>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Knowinnovation/kitime/issues/19#issuecomment-122090353>
> .
>


-- 
David Lomas
e: david.lomas@knowinnovation.com
w: www.knowinnovation.com
s: pale-ed
m: +44 7801 093 869

**Comment by andyburnett** [comment]
Hi Dave,

I like your suggestion. And, I think it deserves a wider audience, so I
will write a script to post your suggestion on a bunch of other projects.

In the meantime, I will send you the install link. Of course, once you have
actually experience the app, you will no longer be able to make insightful
observations - ah the price of progress.

**Comment by dsl101** [comment]
Excellent. I look forward to seeing how long the teams have left to present
their ideas 5 time zones away. And, I also like the possibility that
soapboxes could be timed by people on different continents. I presume the
app adjusts for transatlantic round trip times?

**Comment by andyburnett** [comment]
Ah, funny you should ask. Drew has built in latency compensation. He has
also built in speaker acceleration to make sure the two meet in the middle

**Comment by drewsdunne** [comment]
I do like the idea of having a sign in button rather than a whole screen. So if authenticated, you can delete and do whatever, but if not it takes a view only state.
