### ISSUE TITLE
Maybe, the timer view should show the time of the various timers

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/kitime#8]
This is a 'would be nice to have maybe...' feature.  I like the timer view, and I can see the situation where one might be running multiple timers simultaneously. For instance, we might send groups off to work, and they may have gone at different times (this is a bit contrived, but it could happen). So, we might be running different timers.

So, if it were possible to show the time in the timers view, that might be good.  Also, it might be good to be able to get back to the timers view - without stopping the clock - from the clock view. However, this is a minor point.

**Comment by drewsdunne** [comment]
Yeah I added that because I didn't want someone to not be in control of a timer, kind of as a safety. But if you want the ability back I can easily put that in. The thing that worries me about having the time on the tableview cells is that it would just open up a window for a lot of bugs. I could do it no problem, but it may lengthen the time needed to test the app to completion. If everything else is finished, and I can find a way to do it without and clear bugs I'll definitely implement that.

**Comment by andyburnett** [comment]
I agree. Let's avoid feature creep, and leave this for version 2!
